### ISSUE TITLE
Missing formatters when using AMD in browser

### ISSUE THREAD

**Issue by donnielrt** [benjamine/jsondiffpatch#83] opened 2015-04-28 00:41 UTC
The `jsondiffpatch.formatters` object doesn't seem to get set when using jsondiffpatch (with require.js). Seems like this might the culprit:

https://github.com/benjamine/jsondiffpatch/blob/master/src/main.js#L52

We don't seem to be attaching the formatters for the browser. I've confirmed that adding them in there makes the formatter available.

**Comment by mparpaillon** [comment] 2015-05-15 13:44
I think I have the same issue with Browserify.
The formatters are not set for the same reason

**Comment by benjamine** [comment] 2015-06-16 21:45
I guess I never tried this using AMD, on the [Demo page](http://benjamine.github.io/jsondiffpatch/demo/index.html) you can see I just included them after the main bundle, and you can see by looking at that page sources that they get attached automatically.

I'm not sure there's a simple way to make both files support AMD, maybe because they use CommonJS internally, so in a browser the `require` function is redefined by Browserify.

So, in theory, if you load both files in order (first jsondiffpatch.min.js and then jsondiffpatch.formatters.min.js) and prevent require.js (if that's the loader you're using) from removing jsondiffpatch global, this should just work.

Finally there might a simpler solution which is loading the "full" bundle available at: https://github.com/benjamine/jsondiffpatch/tree/master/public/build
that bundle includes the builtin formatters (and google diffmatchpatch lib for text diffing)

**Comment by donnielrt** [comment] 2015-06-18 22:38
@benjamine I seem to recall encountering this with the full bundle as well

**Comment by toxickg** [comment] 2016-05-14 12:00
@benjamine, I can confirm that including the full bundle doesn't make formatters available as well.

**Comment by benjamine** [comment] 2016-06-06 22:19
you can check the demo page, http://benjamine.github.io/jsondiffpatch/demo/index.html which uses all formatters (in the tabs at the bottom), 
that page has this on the head:
``` html
  <script type='text/javascript' src='../build/jsondiffpatch.min.js'>
  </script>
  <script type='text/javascript' src='../build/jsondiffpatch-formatters.min.js'>
  </script>
```
can you guys provide an example to reproduce this issue?

**Comment by hiwanz** [comment] 2017-08-29 06:13
why not integrate formatters into main,so we can import and use it smoothly after npm install.

`npm install jsondiffpatch`

then use it in es6 way

`import jsondiffpatch from 'jsondiffpatch'`

**Comment by Methuselah96** [comment] 2023-08-26 19:23
I believe formatters are now available through the main bundle. I'm going to close this issue, let me know if there are still remaining issues with the current solution.

**Closed by Methuselah96** 2023-08-26 19:23 UTC
